<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<div class="pagination">';
$config['full_tag_close'] = '<div>';

$config['first_link'] = 'First';
$config['first_tag_open'] = '';
$config['first_tag_close'] = '';

$config['last_link'] = 'Last';
$config['last_tag_open'] = '';
$config['last_tag_close'] = '';

$config['next_link'] = 'Next';
$config['next_tag_open'] = '';
$config['next_tag_close'] = '';

$config['prev_link'] = 'Prev';
$config['prev_tag_open'] = '';
$config['prev_tag_close'] = '';

$config['cur_tag_open'] = '<a class="active" >';
$config['cur_tag_close'] = '</a>';


$config['num_tag_open'] = '';
$config['num_tag_close'] = '';


/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-27 14:08:27 */
/* http://harviacode.com */
